### ISSUE TITLE
Could not find gem 'tabula-api (>= 0) ruby' in source at /root/tabula-api.

### ISSUE THREAD

**Issue by michliu** [tabulapdf/tabula-api#5]
root@ubuntu1404:~/tabula-api# bundle install
Fetching gem metadata from http://rubygems.org/..............
Resolving dependencies...
Could not find gem 'tabula-api (>= 0) ruby' in source at /root/tabula-api.
Source contains 'tabula-api' at: 0.0.1

**Comment by jeremybmerrill** [comment]
Hi @michliu, `tabula-api` was only ever an experiment; it's never been finished. I recommend you check out `tabula-java`.
